### ISSUE TITLE
Occasional unresponsive toggle 

### ISSUE THREAD

**Issue by voodoo6** [jakiestfu/Snap.js#10]
Hi again!

I've noticed that when clicking the open menu link _with a mouse_ the trigger doesn't always close on the second click on the menu link icon.

This is noticeable on the default demo page - click on the menu icon to open then click on it again to close - it doesn't always respond to the second click for me?

Note that this _does not_ appear to happen using touch, only with mouse?

Do you notice the same behaviour?

**Comment by jakiestfu** [comment]
Hello! Open as many issues as you'd like, good sir!

That is because that button is strictly an open button, but you can make a toggle button like this: https://github.com/jakiestfu/Snap.js#toggles

**Comment by voodoo6** [comment]
Sorry! missed that in the docs.. no more issues tonight I promise ;)
