### ISSUE TITLE
Cannot read property 'style' of null

### ISSUE THREAD

**Issue by leighton-tidwell** [jakiestfu/Snap.js#100]
The slide function isnt working at all.. This is so complicated to setup..
Every time i click my toggler. I get this:
Uncaught TypeError: Cannot read property 'style' of null snap.js:97
utils.canTransform snap.js:97
action.translate.easeTo snap.js:198
open snap.js:487
onclick

**Comment by leighton-tidwell** [comment]
The error seems to occur on

canTransform: function(){
                return typeof settings.element.style[cache.vendor+'Transform'] !== 'undefined';
            },

**Comment by jakiestfu** [comment]
Paste the code you're using to initialize Snap

**Comment by leighton-tidwell** [comment]
``` javascript

            var snapper = new Snap({
                element: document.getElementById('content')
            });
        var addEvent = function addEvent(element, eventName, func) {
    if (element.addEventListener) {
        return element.addEventListener(eventName, func, false);
    } else if (element.attachEvent) {
        return element.attachEvent("on" + eventName, func);
    }
};

addEvent(document.getElementById('slider'), 'click', function () {
    if (snapper.state().state == "left") {
        snapper.close();
    } else {
        snapper.open('left');
    }
});
```

**Comment by jakiestfu** [comment]
Do you have an element with `id="content"`?

**Comment by leighton-tidwell** [comment]
Yes, its my main content page.. 

What I do is include "settingmenu.php" into the main file (settingmenu.php contains the above code and some html).

**Comment by leighton-tidwell** [comment]
In firefox console, I get settings.element is null

**Comment by jakiestfu** [comment]
Can you send me a live link to view?

**Comment by leighton-tidwell** [comment]
Uh, not that I'd be safe in showing you, no..

If you have skype or something like that, I can show you over that?

**Comment by leighton-tidwell** [comment]
I can send you the source code of the page, if you'd like?

**Comment by jakiestfu** [comment]
Send me an email at jakie8 (at) gmail (dot) com

**Comment by baerkins** [comment]
I am also having this issue. Was there a solution?

Console error:

```
Uncaught TypeError: Cannot read property 'style' of null
  utils.canTransform
  action.translate.get.matrix 
  state
  (anonymous function)
  x.event.dispatch
  v.handle
```

Error occurs on line 96 in snap.js:

```
canTransform: function(){
  return typeof settings.element.style[cache.vendor+'Transform'] !== 'undefined';
},
```

I use grunt to concatenate into a dev file. Site runs on  WP. I can provide a link if needed.

**Comment by barsv** [comment]
i had this issue and the cause was that i was initializing the snap.js before all DOM elements were loaded into a ui-view by angularjs. i moved my initialization code to the right controller and it started to work.
