### ISSUE TITLE
Open/Close hooks aren't called

### ISSUE THREAD

**Issue by Frexuz** [jakiestfu/Snap.js#102]
Code isn't running:

``` js
  snapper.on("open", function(){
    console.log("open!");
  }).on("close", function(){
    console.log("close!");
  });
```

I seems like these lines are missing in their respective open and close functions:

```
  utils.dispatchEvent('open');
  utils.dispatchEvent('close');
```

**Comment by jakiestfu** [comment]
Are you sure? Open is [here](https://github.com/jakiestfu/Snap.js/blob/master/snap.js#L479) and close is [here](https://github.com/jakiestfu/Snap.js/blob/master/snap.js#L498)...

**Comment by Frexuz** [comment]
Not there in 1.9.0, or something weird happened, but I'll update :) Thanks.
