### ISSUE TITLE
Can't close with flick when disabling a side

### ISSUE THREAD

**Issue by riasvdv** [jakiestfu/Snap.js#11]
As the title says, when you disable one of the sides in the settings it's not possible anymore to close the tray by swiping in the opposite direction as you opened it. Can only be closed with tapping then.

**Comment by jakiestfu** [comment]
You're correct. Will look into this fix ASAP, thanks!

**Comment by jakiestfu** [comment]
Fixed: 6b676e895cb7725f892da4c0295f1a8cbd78e90e
