### ISSUE TITLE
snap right opened by default on big screen

### ISSUE THREAD

**Issue by Joseanmola** [jakiestfu/Snap.js#111]
Hi!
I wonder if it is posible to let the snap right opened while the screen is big.
Something like this:
https://www.hellou.com/offer/shopping-and-lifestyle/leeds
The left menu is opened when the screen is big, but it transforms when the size screen decrease..

THX!

Josean

**Comment by jakiestfu** [comment]
I'm pretty sure this is the lovely work of @voodoo6. It's simple responsive queries, if I'm not mistaken.
