### ISSUE TITLE
snapper.state().state = closed even when it's open

### ISSUE THREAD

**Issue by jaywolters** [jakiestfu/Snap.js#114]
I checked this with your demo which uses 1.9.0 and the behavior is this:

From the console:

snapper.open('left');  // opens the left side - ok
snapper.state().state; // returns 'left'

I am using 1.9.2 and the behavior is a not the same:

snapper.open('left');  // opens the left side - ok
snapper.state().state; // returns 'closed' - not ok

This is effecting my toggle button logic and prevents the toggle from closing because it doesn't evaluate to 'left' I don't understand why this is happening without digging through the source - but I thought I would raise this issue and see if you had any insight.

**Comment by jaywolters** [comment]
this is so very frustrating  - sorry for the alarm. somehow this is evalutating to Left now and my toggle is working.
Its still puzzles me how it got jacked up.

Please disregard this issue - and i will try to provide more insight about the problem before posting again.

**Comment by jakiestfu** [comment]
Do you think you were calling `state().state` before it was done animating?

**Comment by jaywolters** [comment]
I was doing all this in the console trying to figure out why it wouldn't close when I clicked the toggle button.
I would open it, close it and check snapper.state().state each time to see what was going on. it kept saying "closed" when I would do it. I doubt that it was happening before the animation finished - but I suppose its possible. I swore at the screen and went to get coffee. After working on some other features for my project I noticed that the toggle was working again and I chalked it up to "aliens".  I cant reproduced it now and everything seems fine.

Sorry about the false alarm.

Thanks Jake!

**Comment by jakiestfu** [comment]
@jaywolters Hahaha you got it Jay!

**Comment by benjaminalevy** [comment]
I found this error occurred when I was working on a retina macbook and then when I resized the browser from full screen to something smaller, it fixed the problem.

**Comment by aaronstaves** [comment]
Realize I'm about 8 months late to the party, but figured I would comment and save someone the 30 mins I just spent debugging this.  

I can reproduce this on chrome 34 under OS X by zooming in (cmd+shift+'+') and toggling the menu.  Setting the screen size back to normal (cmd+0) fixes it.  This might explain why this was intermittent for @jaywolters above.  Maybe he was possibly zoomed in on a page, forgot about it, then the problem later cleared itself when he reset the zoom level.

Not sure if this is a bug so much as a user issue.  Either way, maybe this will help someone else.

**Comment by benlinton** [comment]
Thanks @aaronstaves, you're a life saver.  I ran into the same issue.  

When zoomed in `snap.state().state` returns `"closed"` even when zoomed in only once (using chrome version 36.0.1985.125).

**Comment by dziulius** [comment]
I seem to be able to reproduce this on chrome 43 when using devices emulator. When emulating iPhone 6 it works just fine, but when emulating iPhone 6 plus - state always returns closed.
