### ISSUE TITLE
iOS - Flash of menu on load

### ISSUE THREAD

**Issue by zanedev** [jakiestfu/Snap.js#117]
On load the menu flashes before it loads the content on ios.  You can see it briefly in the demo on ios simulator it flashes the black menu before it loads the content.

It's more apparent in my project because the overall html is heavier than the demo so I'd like to figure out a solution if possible.

I've tried things like setting display none until after render but nothing seems to work.  Just wondering if you have any insight on how to address this?

**Comment by mvhecke** [comment]
I've fixed this by adding `style="display: none"` to the `snap-drawer` and settings the `snap-drawer` back to `display: block;` in you css file. Not the best solution, but it does the trick for me.
