### ISSUE TITLE
Android 2.3.x Webkit & Firefox Mobile

### ISSUE THREAD

**Issue by grigio** [jakiestfu/Snap.js#12]
Hi I tested it on Android:

Webkit
The swipe transition starts but it's impossible to access to the menu

Firefox Mobile
It works but some areas are not repainted

**Comment by jakiestfu** [comment]
Will look into these, thanks!

**Comment by jakiestfu** [comment]
Should be [fixed](https://github.com/jakiestfu/Snap.js/commit/06a787a7d951ea7decd7fb0681f3131bc41f830f). Let me know if you're still having problems!

**Comment by grigio** [comment]
Yes, your fix work, but now 2 (probably related bugs) are out.
- "no drag area" drags
- The dark side menu isn't scrollable
