### ISSUE TITLE
Problem with Sticky Nav

### ISSUE THREAD

**Issue by messyp** [jakiestfu/Snap.js#126]
This seems an obvious feature which i have got working with other side toolbars but not snap.js

I have a sticky navbar and a sticky footer which always show and the content scrolls underneath. This works fine using position:fixed in the css....

However to make it work with snap.js the navbar and toolbar need to be inside the content div which is positioned absolutely and breaks the stick nav/footer,

The only way around i can find is to keep the navbars outside of the content div and just have the menu slide underneath but this is not ideal and not the same functionality as facebook etc...

...Any thoughts?

**Comment by jakiestfu** [comment]
Think about the layout that Snap.js represents, something deeper than just the surface pane. Think "layers". You have a content layer, and a snap drawer layer. They interact independently from one another, yet they lay above one another. This calls for both layers to be positioned absolutely, and everything within one or the other.

That being said, your top layer (the content layer), can have the fixed elements you describe within them if I'm not mistaken. If I am mistaken, and fixed elements will not translate when their absolute parent does, then why not set your toolbar, footer bar, and content area to three absolute elements as well? Problem solved?

**Comment by messyp** [comment]
The problem is that when you scroll the page, the fixed footer/navbar scroll with the document and do not stay fixed when positioned absolutely. I have not been able to find away around this. This is contrary to the behaviour of say facebook etc, i notice in your demos that the nav always scrolls as opposed to the common fixed nav behaviour used with this kind of menu

**Comment by jakiestfu** [comment]
@messyp With those three absolute elements, the only one that allows scrolling is the content one. Why scroll entire body element with fixed navs if that's counter-productive to an app-like layout? The only things that should scroll are the direct elements you want to be scrolled.
