### ISSUE TITLE
iOS7 Safari chrome

### ISSUE THREAD

**Issue by jdmiller82** [jakiestfu/Snap.js#137]
Just noticed in testing that the way snap.js is set up to handle the content and drawers prevent's Safari's chrome to "shrink" when you start scrolling down

**Comment by serenekhaos** [comment]
Hi,

The following CSS modifications worked for me on a couple of projects but may depend on your setup.

body 
{
    height: auto;
    position: relative;
}

#content of .snap-content
{
    position: relative; /\* instead of position: absolute as defined in snap.css */
}

Good luck,
Kelvin

**Comment by jdmiller82** [comment]
Thanks Kelvin, these modifications helped.
