### ISSUE TITLE
Override clicks/touches to content element when shelf is open

### ISSUE THREAD

**Issue by nikolaiwarner** [jakiestfu/Snap.js#14]
When a shelf is open, touching the content element (if tapToClose is enabled) should only do tapToClose and ignore actual clicks to the content element. 

For example, currently if a user taps the content element expecting to close the shelf but in the process they hit a link or button on the content element instead they will follow that link instead of closing the shelf.

Perhaps adding an invisible overlay to the content element to catch clicks?

**Comment by jakiestfu** [comment]
I actually did this, I just haven't pushed to the demo pages yet. This is what solved the problem: https://github.com/jakiestfu/Snap.js/blob/master/snap.js#L318

**Comment by jakiestfu** [comment]
Er, that's on the demo already. You're still having these problems? The ratchet demo does not follow links...

**Comment by nikolaiwarner** [comment]
Haha, awesome. +1

I haven't updated to 1.6.0 yet. I'll let you know if there's trouble.

**Comment by jakiestfu** [comment]
Dope!
