### ISSUE TITLE
Plugin still under development

### ISSUE THREAD

**Issue by confile** [jakiestfu/Snap.js#148]
is this plugin still under development?

**Comment by arippberger** [comment]
+1

**Comment by cevatkerim** [comment]
+1

**Comment by rascojet** [comment]
Is working

**Comment by jakiestfu** [comment]
This is still under development, not actively though. My apologies, I have so much on my plate right now that I cannot reallocate time to this project at the time.

**Comment by jakiestfu** [comment]
This plugin is (for the time being) under active development until a stable v2.0 has been published, then I might slither away again. Thanks!
