### ISSUE TITLE
Fixed background not loaded on iDevices

### ISSUE THREAD

**Issue by draklane** [jakiestfu/Snap.js#154]
Hi,

Congrats for Snap ! 

On the other side I have a problem with fixed background on iDevices.

The fixed background images do not appear on iDevices. They are not loaded. Everything works fine on PC. What should I do ?

**Comment by jakiestfu** [comment]
It doesn't quite sound like this is an issue with Snap.js. I'm closing for now, correct me if I'm wrong. Hope you found your solution
