### ISSUE TITLE
hasTouch check will disable mouse support on touchscreen laptops

### ISSUE THREAD

**Issue by dfreedm** [jakiestfu/Snap.js#16]
On machines like the Chromebook Pixel (which have both mouse AND touch event support), the hasTouch check will disable mouse usage.

**Comment by jakiestfu** [comment]
Really, the mouse support was mostly so people can demo the code on their computer. Though I feel mouse support is important, is it really necessary to support the mouse still if the device is touch capable?

**Comment by jakiestfu** [comment]
I've thought about this and I've decided that supporting both touch _and_ mouse events at the same time does not coincide with the nature of this script. If you provide some solid use cases where mouse support would be needed alongside touch support, we can reopen this issue.
