### ISSUE TITLE
Tab menu like the demo gif video

### ISSUE THREAD

**Issue by kendichev** [jakiestfu/Snap.js#162]
Hi it is a great example and works just fine. Thanks a lot for it. I have difficult to integrate
a tab layouts just like facebook twitter and also on the demo gif video is tab menu on the top.
Any suggestions, can you help me find out?
Thanks in advance

**Comment by jakiestfu** [comment]
Snap.js v2.0 will have support for richer layouts with minimal effort. Stay tuned for it!
