### ISSUE TITLE
Possible to keep body content centered?

### ISSUE THREAD

**Issue by bradcurnow** [jakiestfu/Snap.js#164]
Hi there! Great work on this, I absolutely love it. After a day of searching and comparing drawer menus I honestly think this is the slickest.

I wonder if it's possible to keep the body content centered as the "menu" expands (see image). I understand the content actually sits on a Z shelf that slides, but would it be possible to "squeeze" this instead of slide? Or perhaps provide a class which takes its width from something like  screenwidth - menuwidth?

My thinking is for desktop and tablet instances where there's a lot of white space either side. As the page width decreases, then the content pushes off as it currently does.

Does that make sense?

To try and explain in scrap code it might look something like this:

``` html
<div id="contentWrapper" style="width:screen-menu; overflow:hidden;">
   <div id="mainContent" style="width: 700px; margin-left/right: auto">
      CONTENT
   </div>
</div>
```

Thanks! Is there any way I can donate to the project or otherwise render assistance? I can only hack at code but if you need graphics of any kind, let me know :)

![possible](https://f.cloud.github.com/assets/5379872/1963725/508082bc-82a1-11e3-81d6-658a898702a8.png)

**Comment by jakiestfu** [comment]
This is a matter of writing your own custom CSS as you would any library. The new version of Snap.js will support richer layouts with minimal effort on your part.

**Comment by bradcurnow** [comment]
Okay thanks mate :)
