### ISSUE TITLE
Snap.js demo toggle open button opens and closes on mobile but not on desktop browser

### ISSUE THREAD

**Issue by aaduane** [jakiestfu/Snap.js#165]
Tested on Firefox and Chrome on my Windows desktop. 

URL: http://jakiestfu.github.io/Snap.js/demo/apps/default.html

Works fine on mobile (slides open and closes) but on desktop it only slides open and then it won't close. 

Anyone know why this is? I don't need it to run perfect on desktop but it would be nice to be able to have it close if someone HAD to use the website on a desktop.

**Comment by Snowbell92** [comment]
@AzzyDude24601 did you find the solution? I am having the same problem.

**Comment by aaduane** [comment]
@Snowbell92 It was some time ago so I can't remember specific details, but if I recall correctly I could not fix the problem and decided to use a different library.

**Comment by Snowbell92** [comment]
@AzzyDude24601 oh! Would you mind telling me which library you used, if you remember it?

**Comment by aaduane** [comment]
@Snowbell92 I started using [Angular](https://angularjs.org/) and then [Angular Materials ](https://material.angularjs.org/latest/getting-started). Things like Angular's ngAnimate made this stuff very easy.
