### ISSUE TITLE
add option to disable drag on mouse events

### ISSUE THREAD

**Issue by jakubweber** [jakiestfu/Snap.js#168]
https://github.com/jamuhl/Snap.js/commit/f3e076cf02767293969c1e33d91ee24ab53f4823

Can you add to the latest version of Snap.js this feature?

**Comment by jakiestfu** [comment]
This is added in v2.0, thanks

**Comment by alexdabast** [comment]
Could you please provide a sample on how to disable mouse and only keep touch feature ?
Thanks

**Comment by jakubweber** [comment]
"clickToDrag: false" should work
