### ISSUE TITLE
Drag and closing the drawer doesn't work with version 1.6.2

### ISSUE THREAD

**Issue by teuneboon** [jakiestfu/Snap.js#17]
Recently wanted to try to use this in a project and noticed that the example didn't work correctly. I could only open the drawer by clicking on the menu icon(dragging didn't work) and I couldn't close the drawer. Reverting to version 1.6.1 solved all issues.

Tested this in both Chrome and Firefox.

**Comment by jakiestfu** [comment]
This was a stupid error on my part. Shouldn't have pushed last night, thanks for the heads up! 09eb964a2ec47a2caa55b673e8fbe128e4b98b19
