### ISSUE TITLE
When toggle button is tapped in the header to open the sidebar the content page jumps to top.

### ISSUE THREAD

**Issue by nodkrot** [jakiestfu/Snap.js#175]
The plugin is great!

However, when i implemented fixed header and press toggle button in the header to open the sidebar the content page jumps to top. Any way to prevent that?

**Comment by jakiestfu** [comment]
Sure. If you're using a link that has an href attribute set to "#", it will cause this jump. Simply call `e.preventDefault()` on your click event. Snap.js v2.0 will add support for easier ways to toggle things.
