### ISSUE TITLE
add option to change display mode

### ISSUE THREAD

**Issue by fredericgrati** [jakiestfu/Snap.js#176]
Is it possible to have the panel on the content ? (overlay)
It shoud be great to have the same display option than JQuery mobile: https://api.jquerymobile.com/panel/#option-display

**Comment by jakiestfu** [comment]
Snap.js currently does not have any other methods for revealing content other than the "reveal" approach. The "push" approach and "overlay" approach would be great additions, but are not planned in a release at the moment, thanks.
