### ISSUE TITLE
Changing element

### ISSUE THREAD

**Issue by th0th** [jakiestfu/Snap.js#188]
I am trying to use Snap.js in my project that is built with jQuery Mobile.

For those who are not familiar with jQuery mobile's HTML structure, jQuery mobile body tag consists of multiple pages (defined by data-role="page" attribute) in a single file and switching from one page to another page is done by simple linking (like <a href="#page-main">Something</a>).

The problem is, if i attach snapper to one of the pages it doesn't appear when I navigate to other pages. Wrapping all pages by another element is not an option since it messes with jQuery mobile options.

I am thinking that, hooking a function to jQuery Mobile's 'pagechange' event, and re-initiating snapper every time page is changed. But this doesn't seem to be the best solution. Do you have any suggestions?

**Comment by gercheq** [comment]
Ditch jQueryMobile and use Snap.js with Bootstrap and Backbone.

On Wednesday, April 9, 2014, H.Gökhan Sarı notifications@github.com wrote:

> I am trying to use Snap.js in my project that is built with jQuery Mobile.
> 
> For those who are not familiar with jQuery mobile's HTML structure, jQuery
> mobile body tag consists of multiple pages (defined by data-role="page"
> attribute) in a single file and switching from one page to another page is
> done by simple linking (like Something <#14548f8213cd817f_page-main>).
> 
> The problem is, if i attach snapper to one of the pages it doesn't appear
> when I navigate to other pages. Wrapping all pages by another element is
> not an option since it messes with jQuery mobile options.
> 
> I am thinking that, hooking a function to jQuery Mobile's 'pagechange'
> event, and re-initiating snapper every time page is changed. But this
> doesn't seem to be the best solution. Do you have any suggestions?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jakiestfu/Snap.js/issues/188
> .

## 

-- Gerçek

**Comment by th0th** [comment]
I solved my problem re-instantiating a new snapper with the new active page when the page is changed.
