### ISSUE TITLE
Put the demo on a dedicated, fullscreen page

### ISSUE THREAD

**Issue by Prinzhorn** [jakiestfu/Snap.js#2]
I can't really try out the demo, because when I try to slide, the whole browser content slides. And the demo box is so tiny. Please let me open the demo on a new page which contains it fullscreen (meta viewport etc.).

**Comment by jakiestfu** [comment]
Did you not see the lk k directly above the demo viewport that says view on iPhone? It opens it In its own window. I thi k I may redo the entire demo page though

**Comment by Prinzhorn** [comment]
Now I see it. But it doesn't look like a link at all.

**Comment by jakiestfu** [comment]
I am going to redo the entire demo page, especially since this got a lot of exposure lately. I will close this issue when that is done, thanks!

**Comment by Prinzhorn** [comment]
Great. Keep up the good work.

**Comment by jakiestfu** [comment]
Updated the demos!
