### ISSUE TITLE
Snap.js with jQuery Mobile

### ISSUE THREAD

**Issue by frankie-loves-jesus** [jakiestfu/Snap.js#204]
Is there a way to combine Snap.js with jQuery Mobile?

Trying here -- http://jsfiddle.net/frank_o/vZBzD/4/ -- but not having much luck.

**Comment by frankie-loves-jesus** [comment]
Turns out I just had to move `.snap-drawers` outside the jQuery Mobile page.

Many thanks to @nitishdhar.

**Comment by nitishdhar** [comment]
@frankie-loves-jesus - thanks for the mention. For others reference here's how I suggested to use Snap.js with jQuery Mobile - http://stackoverflow.com/questions/23875815/jquery-mobile-and-snap-js-as-panel-replacement/23876216#23876216
