### ISSUE TITLE
Toggle not working correctly

### ISSUE THREAD

**Issue by matmac** [jakiestfu/Snap.js#207]
I have set up SnapJs on my Phonegap project when i clicj the dragger it opens but when i click again it doesn't close, this is the code i added:

```
$('#menu').on('click', function() {
    var data;
    data = snapper.state();
    if (data.state === 'left') {
      console.log('is left');
      return snapper.close();
    } else {
      console.log('is right');
      return snapper.open("left");
    }
  });
```

The thing is i get the logs saying IS LEFT, but the panel never closes...

I have even deleted all the surrounding HTML elements leaving only the basic stuff and even though it doesn't close.

I don´t know what else to do.

**Comment by nicolasbonnici** [comment]
Try something like this:

```
                document.getElementById('yourid').addEventListener(
                        'click', function() {

                            if (snapper.state().state == "left") {
                                snapper.close();
                            } else {
                                snapper.open('left');
                            }

                        });
```

Just switch 'yourid' with the correct id name.

**Comment by matmac** [comment]
It was a typo in some other function, sorry...
