### ISSUE TITLE
*REAL* CSS-Only Fix For Z-Index - SOLVED

### ISSUE THREAD

**Issue by justindarc** [jakiestfu/Snap.js#21]
The following CSS resolves the z-index issue on all screen sizes:

```
.snapjs-right .left-drawer,
.snapjs-left .right-drawer {
  display: none;
}
```

In the current solution that you have posted, the overlap of the drawers sometime affects touch events.

**Comment by jakiestfu** [comment]
Good on ya! 21d6315eaba71f29a360c5d0c662fe20c78a0355
