### ISSUE TITLE
enable option

### ISSUE THREAD

**Issue by pgherveou** [jakiestfu/Snap.js#22]
hello Jacob thks for this cool project 

depending of the context I need to enable left, right or both drawers
what do you think about adding a parameter to the disable & enables functions 

this should work?

``` js
        this.enable = function(side) {
            if (side === 'left' || side === 'right') {
                settings.disable = (side === 'left') ? 'right': 'left';
            } else if (side) {
                settings.disable = '';
            }
            if (settings.touchstart) {
                action.drag.listen();
            }
        };
        this.disable = function(side) {
            if (side) {
                settings.disable = side;
            } else {
                action.drag.stopListening();
            }
        };
```

**Comment by jakiestfu** [comment]
Thanks for taking the time to write this up, dude! I was going to make a push later today with a new public method called settings.

``` javascript
var snapper = new Snap();

// Later...

snapper.settings({
    disable: 'right'
});
```

That way you can update more settings than just the disabled one. Thoughts?

**Comment by pgherveou** [comment]
yep, that should work
also I think you should at least verify that you are not enabling dragging in the enable  method

```
this.enable = function(side) {
            if (settings.touchstart) {
                action.drag.listen();
            }
        };
```

I found this shortcuts useful but I can live without it if you expose the settings with a settings method

**Comment by jakiestfu** [comment]
Ah, that way it'd prevent adding listeners twice?

**Comment by pgherveou** [comment]
sorry, maybe its just my use case...
I initialise snap.js with dragging option only on mobile  
I still want to be able to enable or disable the drawers depending of the context of my app later on

**Comment by jakiestfu** [comment]
Oh, I understand what you're saying. I have that check on [line 357](https://github.com/jakiestfu/Snap.js/blob/master/snap.js#L376) with `settings.touchToDrag`.

I will update the repo in a couple hours with the new method, thanks!

**Comment by jakiestfu** [comment]
Added in 1.7.0: e41e068cd0d468659957fd4a98f53d9cdb9accbb

Usage:

``` javascript
snapper.settings({
    disable: 'right'
});
```

This will change the settings and disable the right for you. To revert, use 

``` javascript
snapper.settings({
    disable: 'none'
});
```

**Comment by joaopgrassi** [comment]
What about disable both sides? Just pass two disable options?

**Comment by seven-hong** [comment]
I tried passing "left right" to the options, it failed on both sides, meant both sides were enabled unfortunately.
