### ISSUE TITLE
Press ESC key to close

### ISSUE THREAD

**Issue by xpepermint** [jakiestfu/Snap.js#222]
I don't see this feature. It would be great to have it. Something like this:

```
if (e.keyCode == 27){ snap.close()};
```

**Comment by lesander** [comment]
Just make a loop to wait for the esc keypress and put the `snap.close()` inside. That shouldn't be a feature, it's just a way to use the api. Not that hard to code :wink:

**Comment by xpepermint** [comment]
ok
