### ISSUE TITLE
event emitter

### ISSUE THREAD

**Issue by pgherveou** [jakiestfu/Snap.js#23]
Hi Jacob
I just realised snap.js only accept one callback per event type 
it would be nice to mixin snap.js with an event emitter such as https://github.com/component/emitter
to handle multiple listener, what do you think?

**Comment by jakiestfu** [comment]
Couldn't you do something like this? Or do they get replaced?

``` javascript
snapper.on('drag', myFunc);
snapper.on('drag', anotherFunc);
```

If the drag function does get replaced, I want to keep the weight of this library down as much as possible because it's goal is rather small, (open the menu. that's it, hehe), so I don't want to bloat the library.

What about doing something like this?

``` javascript
snapper.on('drag', function(){
    myFunc.call();
    anotherFunc.call();
});
```

Thoughts?

**Comment by pgherveou** [comment]
i am listening on the animated event to hide/show left or right drawer
but in some scenario I also need to know when the event animated is fired to replace or destroy the content of the drawer. so I do something like that in my updated version

``` js
snapper.once('animated', function() {view.dispose();});
```

nice thing with component.js is that dependencies are shared, thus not impacting global file size
but I understand not everybody is using it ;-) and that you don't want to add dependencies to Snap.js

**Comment by jakiestfu** [comment]
I think I am going to leave it the way it is for now, it's current state should allow you to do what you need to. You'd just need to check in your code if your view actually needs to be disposed, and if it has been, you can do the following:

``` javascript

var view = {
    dispose: function(e){
        if(needsToDispose){
            snapper.off('animated');
            // Dispose shiet
        }
    }
};

snapper.on('animated', view.dispose);
```
