### ISSUE TITLE
Issue with affix of Bootstrap 3

### ISSUE THREAD

**Issue by CoachGodzup** [jakiestfu/Snap.js#239]
Hi,

I'm using snap.js along with Bootstrap 3. I need to have inside the content an inner navbar with affix. It did'n work. It looks like scrolling on window has no effect.

I need to set the data-spy="affix" to trigger at the scrolling of the snap content.

Anyone else has the same issue?

**Comment by frankie-loves-jesus** [comment]
Hi! How would we know? You need to provide a live testcase:

http://css-tricks.com/reduced-test-cases/

**Comment by CoachGodzup** [comment]
Issue solved.

Just I've to read carefully the documentation. In my case I've wrapped the toolbar inside a container like this:

< div id="toolbarContainer" data-spy="affix" data-target=".snap-content" data-offset-top="100">
   [...]
< /div>

Same question on Bootstrap 3, closed 
https://github.com/twbs/bootstrap/issues/14932
