### ISSUE TITLE
Is there a NPM module available for Snap.js ?

### ISSUE THREAD

**Issue by anvk** [jakiestfu/Snap.js#263]
I'm building a REACT app and I would love to use Snap.js in my project but I cannot find NPM module for Snap to include into my project.

**Comment by codeur4** [comment]
snapsvg ?

**Comment by anvk** [comment]
snapsvg description

```
SVG is an excellent way to create interactive, resolution-independent vector graphics that will look great on any size screen. 
```

snap.js description

```
A Library for creating beautiful mobile shelfs in Javascript
```

@codeur4  how are they even similar ?

**Comment by nnur** [comment]
There's this:
https://www.npmjs.com/package/snapjs

**Comment by anvk** [comment]
Closing this issue since NPM module works like a charm.
