### ISSUE TITLE
How to have menu open on page load?

### ISSUE THREAD

**Issue by meganlangston** [jakiestfu/Snap.js#273]
I'm not awesome at JS and I can't for the life of me figure out how to have the menu already open by default on page load. Any tips? Thanks!

**Comment by vitroz** [comment]
Did you find out how?

You just need to create an instance of the component in your script area, and then call the open function.
`var snapper = new Snap({
      element: document.getElementById('content')
    });`

and then:
`snapper.open('right');`
or
`snapper.open('left');`
