### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pageX' of undefined 

### ISSUE THREAD

**Issue by lmartins** [jakiestfu/Snap.js#30]
Hi I'm occasionally getting this error in the console:

   Uncaught TypeError: Cannot read property 'pageX' of undefined 

And the console relates it to the following line in the script:
   cache.startDragX = utils.hasTouch ? e.touches[0].pageX : e.pageX;

Any tips on what it might be?

**Comment by jakiestfu** [comment]
This has been fixed in 1.7.1: fe2aed12221a7525e1eab6a424cf7b434b63d219

It has to do with fault checking to see if specific variables exist.
