### ISSUE TITLE
SnapJS combined with Rachet Push function

### ISSUE THREAD

**Issue by lmartins** [jakiestfu/Snap.js#34]
Im prototyping and mobile app using both tools, managed to get links working with Ratchet's Push function but one thing still wrong.

I have two buttons on the "bar-title" that control both drawers, left and right.

The buttons are something like:
<button class="button" data-toggle-panel="left"><i class="icon-options"></i></button>

and the Javascript:

$('[data-toggle-panel]').click(function(){
    var target = $(this).data();
    snapper.open(target.togglePanel);
});

They all work on the first pageload, but once I open a new page, which again runs through Ratchet's push, the buttons won't work anymore.

The drag events still open the drawers though.

Am I doing something wrong or is there any incompatibility between both tools?

**Comment by jakiestfu** [comment]
You have to re-bind events to your buttons/content area once you push data. I will be working on an update to this soon where you do not have to keep rebinding events

**Comment by lmartins** [comment]
Thanks @jakiestfu, i'll try that

**Comment by jakiestfu** [comment]
``` javascript
var doSnap = function(){
    window.snapper = new Snap({
        element: document.getElementById('content')
    });
};

window.addEventListener('push', doSnap);
```

Live events will be included in the next major update of Snap.js

**Comment by lmartins** [comment]
That did the trick, thank you Jacob

**Comment by jakiestfu** [comment]
@lmartins This actually might be a better approach, see if this works as well:

``` javascript
var doSnap = function(){
    if(window.snapper){
        window.snapper.enable(); // Snap.js already exists, we just need to bind events
    } else {
        window.snapper = new Snap({
            element: document.getElementById('content')
        });
    } 
};

window.addEventListener('push', doSnap);
```

**Comment by lmartins** [comment]
Yep, it works great. Thanks again Jacob :)

**Comment by Extracreative** [comment]
in ratchet template.html what do you change in the script to the above? & does this also close the menu?
