### ISSUE TITLE
Better drag behavior detection.

### ISSUE THREAD

**Issue by alexander-o** [jakiestfu/Snap.js#38]
I was wondering is it possible that there be a better drag behavior implemented to Snap.js? As I modified the demo to fit what I wanted to do with it, I made the content area to be scrollable. However, should I begin dragging the page diagonally (in both mobile and desktop), it becomes confusing already because the menu is opening halfway and the page is scrolling too.

Maybe I'm not doing it right. Please advise. :)

**Comment by jakiestfu** [comment]
What version? There was a definite problem between 1.6.3 and 1.7.8 where you could scroll vertically which would define user intent, but the pane could still be slid open. Try upgrading to 1.7.8 and tell me if this fixes your problem, mate

**Comment by jakiestfu** [comment]
I am fairly certain the problem you're describing is what I think it is, and that issue is now fixed. Let me know if you're still having problems, @alexander-o

**Comment by alexander-o** [comment]
Awesome! Thanks Jakie! Love the update. :dancer: Your plugin has thus far been the best!

**Comment by jakiestfu** [comment]
@alexander-o thanks for the kind words!
