### ISSUE TITLE
IE8/9 support (sorry!)

### ISSUE THREAD

**Issue by voodoo6** [jakiestfu/Snap.js#39]
Hi Jake,
I remember seeing an issue a little while back mentioning support for IE8 and 9 - is there any news on this?

The only thing stopping us using this in production is that the click toggle doesn't work in IE8 or 9 (it works fine in IE10).

We're trying to use snap in a responsive site, so at screen sizes below 980px snap is enabled. While its only a few users that still use narrower widths we have seen enough users using IE8/9 with smaller browser windows to justify needing to support them.

Did you get chance to look into why the open (and close) toggle doesn't respond in these browsers?

Many thanks again!

**Comment by jakiestfu** [comment]
Haha no apologies necessary. I will look into this today, I will say that the only support I can provide for IE 8/9 (possibly even lower) will only open/close the pane, and it will have to use the left/right properties instead of translate3d. I'll look into this today and I'll keep you updated dude

**Comment by voodoo6** [comment]
Open and close is all thats needed!
Much appreciated

**Comment by jakiestfu** [comment]
@voodoo6 I almost have full support for IE9 (minus transitions), but dragging the pane works (using the left property). I'll keep you posted!

**Comment by jakiestfu** [comment]
I've got tested support down to IE7, [reference the readme here](https://github.com/jakiestfu/Snap.js#support), you can view the commit here: b1f8718e44f9f89724530fc86f5f01845cc7f4eb

**Comment by jakiestfu** [comment]
If you want to provide a link to it's use in production, I would love to add it to the readme!

**Comment by voodoo6** [comment]
Great work Jake, looks good on initial test :)
I'll let you know how it goes, apologies again for having to get your hands dirtIE !

**Comment by voodoo6** [comment]
Hi Jake, you mentioned that you would like to see how we got snap working in our site. We're a small start-up company who recently redesigned to produce a responsive site.

Its a work in progress of course but shows you how we got it working (snap kicks in a <980px screen widths)
https://www.hellou.com/Offer/Featured/Leeds

Snap looks to be working great so far - really appreciate your help finding something to try out. It'll be interesting to get feedback from users to see what they think. One thing I've noticed already is that it seems as soon as some people are in a mobile web app they don't expect to be able to do things like swipe to open. I think this will of course change over time as more web apps use the new design patterns that are emerging for responsive sites.

It could also just be a case of communicating the ability to swipe to users, like having an icon or notice that shows that swiping is possible to open the menus.

Anyhow, just a few thoughts.. thanks again, I look forward to seeing how snap develops!

**Comment by jakiestfu** [comment]
Awesome! I like how you're not using the default 266px for it. There have been some great contributions lately, so I look forward to merging them and updating the code. I had to take a breather from developing this, I made it in like, 5 days, haha I am frazzled!

**Comment by voodoo6** [comment]
It's been fun watching it come together, you deserve a breather :)

**Comment by Joseanmola** [comment]
Hi @voodoo6 I saw your website with the snap and I would like to contact you, because I would like to do something like you. The menu still opened until the screen goes smaller..
