### ISSUE TITLE
adding checkbox toggle

### ISSUE THREAD

**Issue by smokingbarrel** [jakiestfu/Snap.js#56]
Is it possible to implement a checkbox toggle which opens the drawer on check and closes the drawer on uncheck. Also this checkbox has to react on alternative ways of opening/closing the drawer (for instance: drag to open the drawer - checkbox checks, tap the content to close the drawer - checkbox unchecks)

Thanks!!!

**Comment by t0rpedo** [comment]
Check this FAQ entry for more info on toggle buttons:
https://github.com/jakiestfu/Snap.js#--how-do-i-make-a-toggle-button

You could add handlers for the 'check' and 'uncheck' actions of the box to toggle the slide. For modifying the checkbox state, you could use some of the event hooks: 
https://github.com/jakiestfu/Snap.js#on-adds-an-event-hook

(i.e. After the 'stop' event you could check the state of the slider:
https://github.com/jakiestfu/Snap.js#state-returns-detailed-information-about-the-state-of-the-pane
and modify the checkbox accordingly)

**Comment by jakiestfu** [comment]
As @t0rpedo states, there is enough logic to hook into Snap.js to create the functionality you're looking for, @smokingbarrel
