### ISSUE TITLE
Add option to prevent dragging futher than maxPosition

### ISSUE THREAD

**Issue by ygor** [jakiestfu/Snap.js#58]
For example, by adding the following:

 // Prevent dragging further than maxPosition
if (settings.maxPosition < (translateTo + translated)) {
  translateTo = settings.maxPosition - translated;
}

**Comment by prud** [comment]
+1 I'd like to see this option as well.

I have been experimenting around with the 3 lines of code you pasted above. The content area is not dragged further than maxPosition, which is great, however trying to drag it again after completely opening it seems buggy.

**Comment by jakiestfu** [comment]
This has been accounted for. Will be included in the next release tonight, thanks!
