### ISSUE TITLE
does not work in any version of IE

### ISSUE THREAD

**Issue by devmondo** [jakiestfu/Snap.js#7]
hi, 
this is one of the best side panels i have ever seen, please make it work in IE

i get this error 
Unable to get property 'snapIgnore' of undefined or null reference 
snap.js, line 155 character 21

thanks in advanced.

**Comment by jakiestfu** [comment]
This is meant for touch devices. Did you intend to use it on a regular website?

**Comment by jasondavis** [comment]
IE on mobile....whaaaaaaaat?

**Comment by voodoo6** [comment]
I use javascript to conditionally load snap.js for smaller screen sizes on a responsive site - so for most cases, the fact that it meant for touch devices allows it to work as expected. However, I suppose it would be good if the toggle worked onClick in IE8+ as it does in other browsers just for the few times an IE user may have a narrow browser window..

Admittedly a fairly edge case but if its an easy fix then I'd vote for it!

**Comment by jakiestfu** [comment]
@voodoo6 I'll look into it, thanks!

**Comment by jakiestfu** [comment]
Silently fails in IE now (no IE support yet, though): 57e94a2ebce58a9b90d4f93274f8cc1034149921

**Comment by devmondo** [comment]
thanks for replies, i know it is for Mobile Devices but as Voodoo6 mentioned, we work on responsive sites and it will really help a lot

**Comment by bstmedia** [comment]
Let me add that it does work in IE10 in Metro and Desktop mode without any issue.  When having ms-touch-actions added .

//just one example
body {
        -ms-touch-action: pan-y;
        }

I like to submit a small fix to make it a kind of compatible with IE9. I don’t expect much touch enabled devices running IE9 anyway. But maybe one older small screen device that should be able to at least toggle the menu. 

// I add a ID identify to right drawer div
<div  id="rd" class="right-drawer absolute">

// and some lines to the easeTo function.
if (typeof cache.vendor=='undefined'){
var jRDindex = document.getElementById('rd').style.zIndex
if (jRDindex == '99') {document.getElementById('rd').style.zIndex = 1;}  
else {document.getElementById('rd').style.zIndex = 99;}  
}

As you can see. I just toggle the z-index which is good enough for my case. I’m sure you guys can make it much nicer than I’m capable todo :)

Thanks for you awesome work!
