### ISSUE TITLE
Feature: only open drawer when dragging from bezel

### ISSUE THREAD

**Issue by prud** [jakiestfu/Snap.js#71]
I could imagine there are some people out there who'd only want the drawer to open when the drag was started from the bezel (outside of the viewport). Don't know how to call such an option.. maybe something like this:

```
dragFromBezel: true/false
```

see http://www.androiduipatterns.com/2012/09/field-trip-app-demonstrates-bezel-swipe.html (but without the indicator)

Just a suggestion, low priority actually..

**Comment by jakiestfu** [comment]
This support has been added with Drag Handle. A user could create a handle on the left or right side of the screen and have dragging activated that way.

If you're talking more about pulling the pane _out_, please reference issue #65 (Hey, you opened that one!) Correct me if I didn't answer your question. Thanks!

**Comment by prud** [comment]
You're right, this is possible through a drag handle. Thanks for clearing this up!

**Comment by t0rpedo** [comment]
@prud,
If possible, could you explain a bit more on what you did to configure the handle to mimic the drag from bezel behavior? 
Thanks!

**Comment by jakiestfu** [comment]
@t0rpedo He probably did something like this. Directly within your content element, add an element like this:

``` html
<div id="right-bezel"></div>
```

<hr />

``` css
#right-bezel{
    position: absolute;
    top: 0;
    bottom: 0;
    right: 0;
    width: 15px;
}
```

<hr />

``` javascript
var snapper = new Snap({
  element: document.getElementById('content'),
  dragger: document.getElementById('right-bezel')
});
```

Again, @t0rpedo, mind you, this is only _truly_ accomplishable by having issue #65 is implemented...

**Comment by prud** [comment]
To be honest I didn't actually implement this, it was just a suggestion :)

**Comment by takrishna** [comment]
Hi  jakiestfu ,

Thanks a lot for Snap.js, Can you please help me with any working example that you may have for this features (right-bezel drawer/dragger)

Also strangely the demo gives me flicks and stranded animation in my phone - HTC Sensation - has dual core processor and ICS running. Facebook/Gmail app slide menu is far richer. Actually when I swipe, the content movement starts and immediately it halts for a second before it resumes the smoothness. Please suggest if there is any performance thread already present Or I would like to start one on it.

**Comment by douson24** [comment]
Can i use a few drag elements?
