### ISSUE TITLE
View Animate In

### ISSUE THREAD

**Issue by whitneyland** [jakiestfu/Snap.js#72]
Hi,

Would like to ask if there has been consideration of "animate in" when switching to a new view.

An example of this can be seen at 0:30 of this video, which shows the Path app:
www.youtube.com/watch?v=cEJvLh099vo

Notice there is also a an animate out for the view covered by the drawer.

Thanks for any feedback,
Lee

**Comment by jakiestfu** [comment]
The API already supports creating flows like this.

``` javascript
ajax.get(url, function(data){
    snapper.expand('right');
    setTimeout(function(){
        document.getElementById('content').innerHTML = data.html;
        snapper.close();
    }, 300);
});
```

**Comment by whitneyland** [comment]
Great!  I did look through the demos, but I know every permutation can't be kept there.  I've going to give it try.  Thanks -
