### ISSUE TITLE
data.snap-ignore via css class

### ISSUE THREAD

**Issue by JohannesRudolph** [jakiestfu/Snap.js#78]
Hi,

I think this would be easy enough to add, but I'd appreciate if we could have a css class (e.g. .no-snap) as an alternative to data-snap-ignore="true".

If you take a look at e.g. the Facebook mobile site, they allow swiping everywhere except on elements that provide swiping themself (e.g. picture galeries). I'd intend to so the same with my App where I display a lot of graphs etc. to which I'm applying the same css anyway, so it would be convenient to do it that way.

What do you think?

**Comment by jakiestfu** [comment]
How is it more convenient than data-snap-ignore="true"?

**Comment by JohannesRudolph** [comment]
Ah damn, you're actually right (been coding too long today...) It'd only
help if I could apply something to that css class that'd allow me to
achieve that behavior. What I basically want is a central place to control
that e.g. all divs that have a chart apply data-snap-ignore=true. I'll
maybe have to write my own angular.js directive or something to enforce
this consistently.
