### ISSUE TITLE
UX Issue using tapToClose

### ISSUE THREAD

**Issue by voodoo6** [jakiestfu/Snap.js#8]
I'm noticing a problem when tapping the content area to close the menu  - if the user taps a link the drawer closes and they get immediately taken to the link tapped.

I think the expected behaviour would be tap the content area to close the menu then tap to choose a link - I'm noticing that in closing the menu, if the user taps an area where there is a link by accident, they get unintentionally taken to the link destination which is confusing.

I believe the facebook app on iOS uses the tap to close first behaviour.

From a UX point of view, maybe it would be helpful to add a transparent overlay (eg. 50% black) over the content area when the drawer opens to indicate that the content area is not accessible until the drawer is closed to reinforce the 'tap first to close' _then_ use the page as normal?

Really great work on this, the best solution I've found for touch menus, looking forward to seeing it develop :)

**Comment by jakiestfu** [comment]
Thanks! This is in the next release that will include various new features and better browser support. If you're looking to fix it for the time being, put this line of code [after line 304](https://github.com/jakiestfu/Snap.js/blob/master/snap.js#L304) and it will disable that link issue.

``` javascript
utils.events.preventDefaultEvent(e);
```

As for styling the content area (50% black, etc), you can use your own CSS classes. For instance, when the left pane is open, a class is added to the body called `snapjs-left` or `snapjs-right`, giving you the ability to add any additional styles based on it's state;)

**Comment by voodoo6** [comment]
Perfect, thanks!

Looking forward to the new version.

**Comment by jakiestfu** [comment]
Fixed: 57e94a2ebce58a9b90d4f93274f8cc1034149921
