### ISSUE TITLE
It scrolls to the right even if it was not suppose to

### ISSUE THREAD

**Issue by loaibassam** [jakiestfu/Snap.js#81]
I see this issue only on iPads, I have disabled to drag to the left and show right side, but on iPads, it actually show it sometimes. Live example here: http://www.webdesignstudents.co.uk/students/loai_shehadeh/LOAI%20Design%20Studio%20Final/index.html

Also is there away to just enable this functions when the screen size is below 800px?

Thanks lot for your help! You have did a great job on this!

**Comment by jakiestfu** [comment]
``` javascript
function applySnap(){
    var width = window.innerWidth;
    if(width<800){
        if(window.snap){
            window.snap.enable();
        } else {
            window.snap = new Snap({
                element: document.getElementById('W')
            });
        }    
    } else {
        if(window.snap){
            window.snap.disable();
        }
    }
}
window.onresize = applySnap;
applySnap();
```
