### ISSUE TITLE
Animation hotness

### ISSUE THREAD

**Issue by voodoo6** [jakiestfu/Snap.js#9]
While I was looking around for an off-canvas menu solution I found another implementation that has a nice animation touch you may like to add to a wish-list ;)

Notice when the menu opens on this example (reduce browser window to see menu link):
http://dbushell.github.io/Responsive-Off-Canvas-Menu/step4.html

It uses a subtle .csstransforms3d to give a really nice feel to the open/close animation (the link is from a [smashing mag article](http://coding.smashingmagazine.com/2013/01/15/off-canvas-navigation-for-responsive-website/))

Another example of something very similar is the native google maps app for iOS - notice the 3d animation effect when opening and closing the right drawer menu.

It's small details but I think it really touches like this add to the 'feel'. Would be nice to see how it works for snap?

**Comment by jakiestfu** [comment]
Snap supports state information.

``` javascript
snapper.state() // returns details information about the panes state
```

From there, you can get the percentage that the pane is open, and apply CSS accordingly. I will test performance of this and if it's looking cool, I will write a demo for multiple animations. Going to push these in a couple hours

**Comment by jakiestfu** [comment]
``` javascript
var snapper = new Snap({
    element: document.getElementById('content')
}),

leftDrawer = document.getElementById('left-drawer'),

applyOtherCSS = function(){
    var percentage = snapper.state().info.translation.percentage;
    if(percentage<=100){
        leftDrawer.style.opacity = percentage*0.01;
    }
};

snapper.on('drag', applyOtherCSS);
snapper.on('animating', applyOtherCSS);
snapper.on('animated', applyOtherCSS);
```

Take this code for example: Every time the pane moves, our function `applyOtherCSS` is fired.

That function retrieves the percentage that the pane is open, multiplies it by `0.01`, and sets the left drawers opacity to that.

This works, but a fundamental attribute of Snap.js is flawed: Updating states. Currently, the state object that is returned from calling `snapper.state()` is updated sporadically throughout the script as opposed to being abstracted away. This not only makes snap.js larger, but makes it more annoying to update the state.

Bringing this all around, this animates beautifully, but when a user **releases** their finger and CSS3 takes the stage in terms of animating, I cannot update the state of the pane unless I were to query it's CSS data every X milliseconds.

Technically, what is flawed is `snapper.on('animating', fn)`, so for the time being, until I can figure out a nicer solution, this idea will have to take backseat.

**Comment by jakiestfu** [comment]
Will look into better way to handle this. Expect it in 2.0 possibly

**Comment by voodoo6** [comment]
I think its these type of details that separate the good from the great.. roll on 2.0!
Cheers for looking into it, look forward to seing what you come up with (if you do ;)

**Comment by jakiestfu** [comment]
I just pushed and included exposing as part of the API, that's probably the newest addition. Plus better browser support

**Comment by ebradbury** [comment]
Hey @jakiestfu,

The on('animating') issue seems to still be present. One option would be switching from CSS transitions to animations and using the `animationiteration` event to update the snapper status.

https://developer.mozilla.org/en-US/docs/Web/Events/animationiteration

Thoughts?

**Comment by ebradbury** [comment]
@jakiestfu I looked into this and `animationiteration` actually only fires at the end of an animation loop. Not for each step along the way. Not going to work. Sorry for the noise.
